spring:
  main:
    banner-mode: off

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.200:8761/eureka/
  instance:
    localhost
    
hello:
  message: Service Two Profile Two
config:
  server: config-server
  
jwt:
  secret: secretkey
  token:
    validity: 980000
